app/models.py
#_*_ coding:utf-8 _*_
from . import db
class Video(db.Model):
    pass
    #表名称
    __tablename__='videos'
    id =db.Column(db.Text,primary_key=True)
    title=db.Column(db.Text)
    duration=db.Column(db.Integer)
    time_created=db.Column(db.Text)
    author=db.Column(db.Text)
    viewed=db.Column(db.Integer)
    remarked=db.Column(db.Integer)
    comments=db.Column(db.Integer)
    remarks=db.Column(db.Integer)
    view_url=db.Column(db.Text)
    img_url=db.Column(db.Text)
    VID_url=db.Column(db.Text)
    file_url=db.Column(db.Text)
    updated=db.Column(db.Text)
    """
    def __init__(self,id,title,duration,time_created,author,
                 viewed,remarked,comments,remarks,view_url,img_url,VID_url,file_url,updated):
        self.id=id
        self.title=title
        self.duration=duration
        self.time_created=time_created
        self.author=author
        self.viewed=viewed
        self.remarked=remarked
        self.comments=comments
        self.remarks=remarks
        self.view_url=view_url
        self.img_url=img_url
        self.VID_url=VID_url
        self.file_url=file_url
        self.updated = updated
    def __repr__(self):
        return '<Video %r>'% self.title
    """

app/forms.py
#_*_coding:utf-8_*_
#from wtforms import Form
from flask.ext.wtf import Form
from wtforms import SubmitField,SelectField,StringField,BooleanField
from wtforms.validators import Required
class NameForm(Form):
    find_type = SelectField(u'查询类型', choices=[('title', '标题'), ('author', '作者')])
    keyword=StringField(unicode(u'请输入查询关键词'),validators=[Required()])
    submit=SubmitField('submit')
class CheckForm(Form):
    choice= BooleanField()
    submit = SubmitField(u'解析')

app/__init__.py
#_*_coding:utf-8_*_
from flask import Flask,render_template
from flask.ext.bootstrap import Bootstrap
from flask.ext.moment import Moment
from flask.ext.sqlalchemy import SQLAlchemy
from config import config
from flask_wtf.csrf import CsrfProtect

#以上为导入的模块,注意扩展通过flask.ext导入的
#暂时没有程序实例,因此扩展没有初始化
bootstrap = Bootstrap()
moment = Moment()
db = SQLAlchemy()
#表单保护
#csrf = CsrfProtect()

#定义初始化方法,传入配置名称
def create_app(config_name):
    app = Flask(__name__)
    #获取配置
    app.config.from_object(config[config_name])
    #从配置初始化APP,注意init_app()方法没有定义
    #config[config_name].init_app(app)

    #初始化扩展
    bootstrap.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    #csrf.init_app(app)
    #蓝本注册到程序APP上
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app


if __name__=='__main__':
    print create_app('default')

app/main/__init__.py
#_*_ coding:utf-8 _*_
from flask import Blueprint

#实例化一个蓝本对象
main = Blueprint('main',__name__)
from . import views,error

app/main/views.py
#_*_coding:utf-8_*_
from flask import render_template,session,redirect,url_for
from .import main
from .. import db
from ..models import Video
from ..forms import NameForm,CheckForm
from parse.parse import Getfile
from flask import request,abort,flash
import re
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
#查询首页
@main.route('/',methods=['GET','POST'])
def index():
    #判断参数
    form=NameForm()
    if form.validate_on_submit():
        type=form.find_type.data
        data=form.keyword.data
        session['find_type']=type
        session['find_para']=data
        #查询
        return redirect(url_for('main.index_page',id=1))
    return render_template('index.html',form=form)
    #return render_template('3.html')

#处理查询结果,分页
@main.route('/index/<int:id>',methods=['GET','POST'])
def index_page(id):
    #获取选择的view_url
    if request.method == 'POST':
        view_urls=(request.form.getlist('get_video_id'))
        for view_url in view_urls:
            getfile=Getfile(view_url)
            getfile.run()
            VID_url=getfile.VID_url
            file_url=getfile.file_url
            VID=getfile.VID
            if VID_url:
                #更新列
                Video.query.filter(Video.view_url==view_url).update({Video.file_url:file_url,
                                                           Video.VID_url:VID_url})
    #查询参数按照空格分割
    para_list=session['find_para'].split(' ')
    list_encode=[]
    for para in para_list:
        #剔除空格
        if para !='':
            para='%'+para+'%'
            para_encode=unicode(para)
            list_encode.append(para_encode)
    #paginate=Video.query.filter(Video.title.like(session['find_para'])).paginate(id,12,False)
    try:
        ob=Video.query
        for i in list_encode:
            if session['find_type']=='title':
                ob = ob.filter(Video.title.like(i))
            elif session['find_type']=='author':
                ob = ob.filter(Video.author.like(i))
        paginate = ob.paginate(id,12,False)
        object_list = paginate.items
        if len(object_list) > 0:
            #return render_template('video.html',pagination=paginate,object_list=object_list)
            return render_template('video.html',pagination=paginate,object_list=object_list)
        else:
            flash('提示:多个关键词以空格分开,如果看到此消息请修改关键词')
            return redirect(url_for('main.index'))
    except Exception:
        flash('对不起,出错了!')

@main.route('/parse/<string:url_id>')
def parse(url_id):
    pass
    #获取播放地址
    videos=Video.query.filter(Video.id==url_id).all()

    video=videos[0]
    getfile=Getfile(video.view_url)
    getfile.run()
    VID_url=getfile.VID_url
    file_url=getfile.file_url
    VID=getfile.VID
    if VID_url:
        #更新列
        Video.query.filter(Video.id==url_id).update({Video.file_url:file_url,
                                                   Video.VID_url:VID_url})
        #设置VID到session
        session['VID']=VID
        session['file_url']=video.file_url
        session['title']=video.title
        return render_template('play.html',VID=session['VID'],file_url=session['file_url'],title=session['title'])
    else:
        return unicode(u'<h1>没有解析到网址</h1>')

@main.route('/play/<string:url_id>')
def play(url_id):
    if url_id !='pre':
        videos=Video.query.filter(Video.id==url_id).all()
        video=videos[0]
        #设置session
        pattern=re.compile('(?<=VID=)\S{1,}')
        session['VID']=pattern.findall(video.VID_url)[0]
        #更新文件地址
        getfile=Getfile(video.VID_url)
        getfile.get_file()
        session['file_url']=getfile.file_url
        #更新到数据库
        Video.query.filter(Video.id==url_id).update({Video.file_url:session['file_url']})
        session['title']=video.title
        return render_template('play.html',VID=session['VID'],file_url=session['file_url'],title=session['title'])
    else:
        #没有播放记录,直接跳转到首页
        flash('没有播放记录!')
        try:
            return render_template('play.html',VID=session['VID'],file_url=session['file_url'],title=session['title'])
        except Exception:
            return redirect(url_for('main.index'))
#查询同一作者上传
@main.route('/author/<string:name>')
def author(name):
    if name:
        para_encode=unicode(name)
        session['find_type']='author'
        session['find_para']=para_encode
        return redirect(url_for('main.index_page',id=1))

    else:
        return redirect(url_for('main.index'))
@main.route('/playlist/<int:id>')
def getplaylist(id=1):

    try:
        paginate=Video.query.filter(Video.VID_url !='').paginate(id,12,False)
        object_list=paginate.items
        return render_template('playlist.html',pagination=paginate,object_list=object_list)
    except Exception:
        flash('没有可以播放的视频,请自行解析!')
        return redirect(url_for('main.index'))

if __name__ == '__main__':
    pass

app/templates/1.html
{% extends "bootstrap/base.html" %}
{% block title %}Flasky{% endblock %}
{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
         <div class="container">
             <div class="navbar-header">
                 <button type="button" class="navbar-toggle"
                  data-toggle="collapse" data-target=".navbar-collapse">
                     <span class="sr-only">Toggle navigation</span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
                     <span class="icon-bar"></span>
</button>
                 <a class="navbar-brand" href="/">Flasky</a>
             </div>
             <div class="navbar-collapse collapse">
                 <ul class="nav navbar-nav">
                     <li><a href="/">Home</a></li>
                 </ul>
             </div>
         </div>
</div>
{% endblock %}
{% block content %} <div class="container">
         <div class="page-header">
             <h1>Hello, {{ name }}!</h1>
         </div>
     </div>
{% endblock %}

app/templates/2.html
{% extends "base.html" %}
{{ super() }}
{% block content %}

<div class="row">
    {% for i in range(20) %}
      <div class="col-md-4">
        <div class="thumbnail">
          <img src="http://pic32.nipic.com/20130829/12906030_124355855000_2.png" alt="...">
          <div class="caption">
            <h3>{{ i }}</h3>
            <p>...</p>
            <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
          </div>
        </div>
      </div>
    {% endfor %}
</div>
{% endblock %}

app/templates/3.html
{% extends "base.html" %}
{% block content %}
<div class="container">
	<div class="row clearfix">
		<div class="col-md-2 column">
		</div>
		<div class="col-md-6 column">
			<div class="row">
				<div class="col-md-2">
					<div class="thumbnail">
						<img alt="300x200" src="http://ibootstrap-file.b0.upaiyun.com/lorempixel.com/600/200/people/default.jpg" />
						<div class="caption">
							<h3>
								Thumbnail label
							</h3>
							<p>
								Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
							</p>
							<p>
								 <a class="btn btn-primary" href="#">Action</a> <a class="btn" href="#">Action</a>
							</p>
						</div>
					</div>
				</div>
				<div class="col-md-2">
					<div class="thumbnail">
						<img alt="300x200" src="http://ibootstrap-file.b0.upaiyun.com/lorempixel.com/600/200/city/default.jpg" />
						<div class="caption">
							<h3>
								Thumbnail label
							</h3>
							<p>
								Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
							</p>
							<p>
								 <a class="btn btn-primary" href="#">Action</a> <a class="btn" href="#">Action</a>
							</p>
						</div>
					</div>
				</div>
				<div class="col-md-2">
					<div class="thumbnail">
						<img alt="300x200" src="http://ibootstrap-file.b0.upaiyun.com/lorempixel.com/600/200/sports/default.jpg" />
						<div class="caption">
							<h3>
								Thumbnail label
							</h3>
							<p>
								Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
							</p>
							<p>
								 <a class="btn btn-primary" href="#">Action</a> <a class="btn" href="#">Action</a>
							</p>
						</div>
					</div>
				</div>
			</div>

				<div class="col-md-2">
					<div class="thumbnail">
						<img alt="300x200" src="http://ibootstrap-file.b0.upaiyun.com/lorempixel.com/600/200/people/default.jpg" />
						<div class="caption">
							<h3>
								Thumbnail label
							</h3>
							<p>
								Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
							</p>
							<p>
								 <a class="btn btn-primary" href="#">Action</a> <a class="btn" href="#">Action</a>
							</p>
						</div>
					</div>
				</div>
				<div class="col-md-2">
					<div class="thumbnail">
						<img alt="300x200" src="http://ibootstrap-file.b0.upaiyun.com/lorempixel.com/600/200/city/default.jpg" />
						<div class="caption">
							<h3>
								Thumbnail label
							</h3>
							<p>
								Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
							</p>
							<p>
								 <a class="btn btn-primary" href="#">Action</a> <a class="btn" href="#">Action</a>
							</p>
						</div>
					</div>
				</div>
				<div class="col-md-2">
					<div class="thumbnail">
						<img alt="300x200" src="http://ibootstrap-file.b0.upaiyun.com/lorempixel.com/600/200/sports/default.jpg" />
						<div class="caption">
							<h3>
								Thumbnail label
							</h3>
							<p>
								Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
							</p>
							<p>
								 <a class="btn btn-primary" href="#">Action</a> <a class="btn" href="#">Action</a>
							</p>
						</div>
					</div>
				</div>
			<ul class="pagination pagination-lg">
				<li>
					 <a href="#">Prev</a>
				</li>
				<li>
					 <a href="#">1</a>
				</li>
				<li>
					 <a href="#">2</a>
				</li>
				<li>
					 <a href="#">3</a>
				</li>
				<li>
					 <a href="#">4</a>
				</li>
				<li>
					 <a href="#">5</a>
				</li>
				<li>
					 <a href="#">Next</a>
				</li>
			</ul>
		</div>
		<div class="col-md-4 column">
		</div>
	</div>
</div>
{% endblock %}}

app/templates/4.html
{% extends "base.html" %}
{{ super() }}
{% block content %}
<div class="container">
    <div class="row clearfix">
        <div class="col-md-2 column">
            <p>这是测试区域</p>
        </div>
        <div class="col-md-8 column">
             <div class="row">
                 {% for video in object_list %}
                <div class="col-md-4">

                    <div class="thumbnail">
                        <img src={{ video.imgs }} width="120" alt={{ video.title }} >
                        <a title={{video.title}}>
                            <span class="title">{{ video.title | truncate(11,True) }}</span></a><br>
                        <span class="info">时长:</span>{{ video.duration }}<br>
                        <span class="info">添加时间:</span> {{ video.time_created }} <br>
                        <span class="info">作者:</span><a href={{ url_for('main.author',name=video.author)}}>{{ video.author }}</a><br>
                        <span class="info">查看:</span> {{ video.viewed }}&nbsp; <span class="info">收藏:</span>{{ video.marked }}<br>
                        <span class="info">留言:</span> {{ video.comments }}&nbsp;<span class="info">积分:</span> {{ video.marks }}<br>
                        {% if video.play_url %}
                            <span> <a href={{ url_for('main.play',url_id=video.id) }}>播放</a></span><br>
                        {% else %}
                            <span><a href={{ url_for('main.parse',url_id=video.id) }}>解析</a></span>
                        {% endif %}
                    </div>

                </div>
                 {% endfor %}
             </div>
             <div class="pagination ">
                <a href="">{{ pagination.page }}/{{ pagination.pages }}</a>
                <a href="/index/1">首页</a>
                {% if pagination.has_prev %}
                    <a href="/index/{{ pagination.prev_num }}">上一页</a>
                {% endif %}
                {% if pagination.page + 1 < pagination.pages %}
                    <a href="/index/{{ pagination.page + 1 }}">{{ pagination.page + 1 }}</a>
                {% endif %}
                {% if pagination.page + 2 < pagination.pages %}
                    <a href="/index/{{ pagination.page + 2 }}">{{ pagination.page + 2 }}</a>
                {% endif %}
                {% if pagination.page + 3 < pagination.pages %}
                    <a href="/index/{{ pagination.page + 3 }}">{{ pagination.page + 3 }}</a>
                {% endif %}
                {% if pagination.page + 4 < pagination.pages %}
                    <a href="/index/{{ pagination.page + 4 }}">{{ pagination.page + 4 }}</a>
                {% endif %}
                {% if pagination.page + 5 < pagination.pages %}
                    <a href="/index/{{ pagination.page + 5 }}">{{ pagination.page + 5 }}</a>
                {% endif %}
                {% if pagination.has_next %}
                    <a href="/index/{{ pagination.next_num }}">下一页</a>
                {% endif %}
                <a href="/index/{{ pagination.pages }}">尾页</a>
             </div>
      </div>
        <div class="col-md-2 column">
            <p>这是测试区域</p>
        </div>
</div>
</div>
{% endblock %}

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Flasky{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Flasky</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">查询</a></li>
                <li><a href={{ url_for("main.index_page",id=1) }}>结果</a></li>
                <li><a href={{ url_for("main.play",url_id='pre') }}>上次播放</a></li>
                <li><a href={{ url_for("main.getplaylist",id=1)}}>播放列表</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
{% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
{% endfor %}
    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flasky{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>你好, 哥们</h1>
</div>
{{ wtf.quick_form(form) }}
{% endblock %}

app/templates/play.html
{% extends "base.html" %}
{% block content %}
<link href="style.css" rel="stylesheet" type="text/css">
    <span>{{ title }}</span></br>
    <span>
    <embed id="91" name="91" width="700" height="450"
       src="http://91.9p91.com/9e.swf?autoplay=false&amp;video_id={{ VID }}&amp;mp4=999"
       quality="high" bgcolor="white" play="true" loop="false" allowscriptaccess="always"
       type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer">

    </span></br>
    <span><a href={{ file_url }}>下载文件</a></span>
{% endblock %}

app/templates/playlist.html
{% extends "base.html" %}
{{ super() }}
{% block content %}
<div class="container">
    <div class="row clearfix">
        <div class="col-md-2 column">
            <p>这是测试区域</p>
        </div>
        <div class="col-md-8 column">
             <div class="row">
                 {% for video in object_list %}
                <div class="col-md-4">

                    <div class="thumbnail">
                        <img src={{ video.img_url|get_img_list}} width="120" alt={{ video.title }} >
                        <a title={{video.title}}>
                            <span class="title">{{ video.title | truncate(11,True) }}</span></a><br>
                        <span class="info">时长:</span>{{ video.duration }}<br>
                        <span class="info">添加时间:</span> {{ video.time_created }} <br>
                        <span class="info">作者:</span><a href={{ url_for('main.author',name=video.author)}}>{{ video.author }}</a><br>
                        <span class="info">查看:</span> {{ video.viewed }}&nbsp; <span class="info">收藏:</span>{{ video.marked }}<br>
                        <span class="info">留言:</span> {{ video.comments }}&nbsp;<span class="info">积分:</span> {{ video.marks }}<br>
                        {% if video.VID_url %}
                            <span> <a href={{ url_for('main.play',url_id=video.id) }}>播放</a></span><br>
                        {% else %}
                            <span><a href={{ url_for('main.parse',url_id=video.id) }}>解析</a></span>
                        {% endif %}
                    </div>

                </div>
                 {% endfor %}
             </div>
             <div class="pagination ">
                <a href="">{{ pagination.page }}/{{ pagination.pages }}</a>
                <a href="/playlist/1">首页</a>
                {% if pagination.has_prev %}
                    <a href="/playlist/{{ pagination.prev_num }}">上一页</a>
                {% endif %}
                {% if pagination.page + 1 < pagination.pages %}
                    <a href="/playlist/{{ pagination.page + 1 }}">{{ pagination.page + 1 }}</a>
                {% endif %}
                {% if pagination.page + 2 < pagination.pages %}
                    <a href="/playlist/{{ pagination.page + 2 }}">{{ pagination.page + 2 }}</a>
                {% endif %}
                {% if pagination.page + 3 < pagination.pages %}
                    <a href="/playlist/{{ pagination.page + 3 }}">{{ pagination.page + 3 }}</a>
                {% endif %}
                {% if pagination.page + 4 < pagination.pages %}
                    <a href="/playlist/{{ pagination.page + 4 }}">{{ pagination.page + 4 }}</a>
                {% endif %}
                {% if pagination.page + 5 < pagination.pages %}
                    <a href="/playlist/{{ pagination.page + 5 }}">{{ pagination.page + 5 }}</a>
                {% endif %}
                {% if pagination.has_next %}
                    <a href="/playlist/{{ pagination.next_num }}">下一页</a>
                {% endif %}
                <a href="/playlist/{{ pagination.pages }}">尾页</a>
             </div>
      </div>
        <div class="col-md-2 column">
            <p>这是测试区域</p>
        </div>
</div>
</div>
{% endblock %}

app/templates/video.html
{% extends "base.html" %}
{{ super() }}
{% block content %}
<div class="container">
    <div class="row clearfix">
        <div class="col-md-2 column">
            <p>这是测试区域</p>
        </div>
        <div class="col-md-8 column">
            <form method="post">
                <div class="row">
                     {% for video in object_list %}
                        <div class="col-md-4">
                            <div class="thumbnail">
                                <img src={{ video.img_url|get_img_list}} width="0" >
                                <a title={{video.title}}>
                                    <span class="title">{{ video.title | truncate(11,True) }}</span></a><br>
                                <span class="info">时长:</span>{{ video.duration }}<br>
                                <span class="info">添加时间:</span> {{ video.time_created }} <br>
                                <span class="info">作者:</span><a href={{ url_for('main.author',name=video.author)}}>{{ video.author }}</a><br>
                                <span class="info">查看:</span> {{ video.viewed }}&nbsp; <span class="info">收藏:</span>{{ video.marked }}<br>
                                <span class="info">留言:</span> {{ video.comments }}&nbsp;<span class="info">积分:</span> {{ video.marks }}<br>
                                {% if video.VID_url %}
                                    <span> <a href={{ url_for('main.play',url_id=video.id) }}>播放</a></span><br>
                                {% else %}
                                    <span><a href={{ url_for('main.parse',url_id=video.id) }}>解析</a></span>
                                    <input type=checkbox name=get_view_url value="{{ video.view_url }}">
                                {% endif %}
                            </div>
                        </div>
                     {% endfor %}
             </div>
            <input type="submit" name="注册">
            </form>
             <div class="pagination ">
                <a href="">{{ pagination.page }}/{{ pagination.pages }}</a>
                <a href="/index/1">首页</a>
                {% if pagination.has_prev %}
                    <a href="/index/{{ pagination.prev_num }}">上一页</a>
                {% endif %}
                {% if pagination.page + 1 < pagination.pages %}
                    <a href="/index/{{ pagination.page + 1 }}">{{ pagination.page + 1 }}</a>
                {% endif %}
                {% if pagination.page + 2 < pagination.pages %}
                    <a href="/index/{{ pagination.page + 2 }}">{{ pagination.page + 2 }}</a>
                {% endif %}
                {% if pagination.page + 3 < pagination.pages %}
                    <a href="/index/{{ pagination.page + 3 }}">{{ pagination.page + 3 }}</a>
                {% endif %}
                {% if pagination.page + 4 < pagination.pages %}
                    <a href="/index/{{ pagination.page + 4 }}">{{ pagination.page + 4 }}</a>
                {% endif %}
                {% if pagination.page + 5 < pagination.pages %}
                    <a href="/index/{{ pagination.page + 5 }}">{{ pagination.page + 5 }}</a>
                {% endif %}
                {% if pagination.has_next %}
                    <a href="/index/{{ pagination.next_num }}">下一页</a>
                {% endif %}
                <a href="/index/{{ pagination.pages }}">尾页</a>
             </div>
      </div>
        <div class="col-md-2 column">
            <p>这是测试区域</p>
        </div>
</div>
</div>
{% endblock %}